### ISSUE TITLE
Reply with feedback on incorrect commands too

### ISSUE THREAD

**Issue by AlexPoulsen** [kartelant/Tupperware#38]
Any time a user triggers a command, or tries to, the bot should send a message indicating that it was received, if it was successful, or if the command doesn't exist.

**Comment by kartelant** [comment]
I didn't add responses on incorrect command usage on principle - in the bot making community such responses are looked down upon due to likelihood of accidental triggering with some custom prefixes, especially in large servers. 

All correctly spelled command invocations are already responded to, unless the bot lacks permissions to send messages to the current channel, so it should be apparent when the problem is a nonexistent/misspelled command.

**Comment by AlexPoulsen** [comment]
yeah sorry, the issue was at first partly a permissions error, but i didn't catch it because the first command was one that no longer exists and the bot didn't respond, leading me to think it didn't respond to any. sorry for the unnecessary issue.

**Comment by kartelant** [comment]
no worries! You did remind me that missing send messages permissions should cause the bot to attempt to DM the user as a fallback ideally, which is something i should add eventually to avoid problems like this in the future
